site_name: Fusion Engine
summary: Fusion Engine documentation
site_url: https://docs.fusion-engine.tech

nav:
  - Home: 'index.md'
  - Wiki: 'wiki/index.md'
  - Api: 'api/index.md'
  - Tutorial: 'tutorials/index.md'
